pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                echo 'Running CI/CD pipeline'
                sh 'whoami'
                sh 'pwd'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    echo "<h1>CI/CD Test Success</h1>" > index.html
                    sudo cp index.html /var/www/html/
                '''
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed'
        }
    }
}
