pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                echo 'Running CI/CD pipeline'
                sh 'whoami'
                sh 'pwd'
                sh 'ls -l'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    echo "Deploying existing index.html to Apache..."
                    # copy index.html from repo (workspace) to /var/www/html
                    sudo cp index.html /var/www/html/
                '''
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
